blank_issues_enabled: true
contact_links:
- name: ğŸ’¬ Discord server
  url: https://discord.iceyleagons.net/
  about: Chat with devs and community
- name: ğŸŒWebsite
  url: https://icicle.iceyleagons.net/
  about: Icicle website
